/* include/bmon/defs.h.  Generated by configure.  */
/* include/bmon/defs.h.in.  Generated from configure.in by autoheader.  */

/* no overflow workaround */
/* #undef DISABLE_OVERFLOW_WORKAROUND */

/* have curses */
/* #undef HAVE_CURSES */

/* Define to 1 if you have the <curses.h> header file. */
#define HAVE_CURSES_H 1

/* Define to 1 if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* have kstat */
/* #undef HAVE_KSTAT */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* have ncurses */
#define HAVE_NCURSES "1"

/* Define to 1 if you have the <ncurses.h> header file. */
#define HAVE_NCURSES_H 1

/* Define to 1 if you have the <ncurses/ncurses.h> header file. */
/* #undef HAVE_NCURSES_NCURSES_H */

/* Define to 1 if you have the <netinet6/in6.h> header file. */
/* #undef HAVE_NETINET6_IN6_H */

/* have libnl */
/* #undef HAVE_NL */

/* have redrawwin */
#define HAVE_REDRAWWIN "1"

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if the system has the type `suseconds_t'. */
#define HAVE_SUSECONDS_T 1

/* Define to 1 if you have the <sys/sockio.h> header file. */
/* #undef HAVE_SYS_SOCKIO_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/utsname.h> header file. */
#define HAVE_SYS_UTSNAME_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* have use_default_colors */
#define HAVE_USE_DEFAULT_COLORS "1"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "tgraf@suug.ch"

/* Define to the full name of this package. */
#define PACKAGE_NAME "bmon"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "bmon 2.0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "bmon"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.0.1"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* operating system */
/* #undef SYS_BSD */

/* operating system */
#define SYS_LINUX "1"

/* operating system */
/* #undef SYS_OTHER */

/* operating system */
/* #undef SYS_SUNOS */

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */
